import 'package:flutter/material.dart';

import '../models/dev_tool.dart';
import '../ui/tool_views.dart';

class ToolRegistry {
  static final List<DevTool> tools = [
    DevTool(
      id: 'unix_time_converter',
      name: 'Unix Time Converter',
      icon: Icons.schedule,
      builder: (_) => buildUnixTimeConverter(),
      category: 'Converters',
    ),
    DevTool(
      id: 'json_format_validate',
      name: 'JSON Format/Validate',
      icon: Icons.data_object,
      builder: (_) => buildJsonFormatValidate(),
      category: 'Formatters',
    ),
    DevTool(
      id: 'base64_string_encode_decode',
      name: 'Base64 String Encode/Decode',
      icon: Icons.code,
      builder: (_) => buildBase64String(),
      category: 'Encoders',
    ),
    DevTool(
      id: 'base64_image_encode_decode',
      name: 'Base64 Image Encode/Decode',
      icon: Icons.image,
      builder: (_) => buildBase64Image(),
      category: 'Encoders',
    ),
    DevTool(
      id: 'compression_codecs',
      name: 'Compress / Decompress',
      icon: Icons.compress,
      builder: (_) => buildCompression(),
      category: 'Compression',
    ),
    DevTool(
      id: 'base_encodings',
      name: 'Base32/58/62/85/Bech32',
      icon: Icons.tag,
      builder: (_) => buildBaseEncodings(),
      category: 'Encoders',
    ),
    DevTool(
      id: 'jwt_debugger',
      name: 'JWT Debugger',
      icon: Icons.vpn_key,
      builder: (_) => buildJwtDebugger(),
      category: 'Security',
    ),
    DevTool(
      id: 'auth_totp',
      name: 'Auth TOTP',
      icon: Icons.lock_clock,
      builder: (_) => buildAuthTotp(),
      category: 'Security',
    ),
    DevTool(
      id: 'regexp_tester',
      name: 'RegExp Tester',
      icon: Icons.search,
      builder: (_) => buildRegExpTester(),
      category: 'Text',
    ),
    DevTool(
      id: 'url_encode_decode',
      name: 'URL Encode/Decode',
      icon: Icons.link,
      builder: (_) => buildUrlEncodeDecode(),
      category: 'Encoders',
    ),
    DevTool(
      id: 'url_parser',
      name: 'URL Parser',
      icon: Icons.link_outlined,
      builder: (_) => buildUrlParser(),
      category: 'Parsers',
    ),
    DevTool(
      id: 'subdomain_finder',
      name: 'Subdomain Finder',
      icon: Icons.travel_explore,
      builder: (_) => buildSubdomainFinder(),
      category: 'Network',
    ),
    DevTool(
      id: 'subdomain_takeover',
      name: 'Subdomain Takeover Check',
      icon: Icons.domain_verification,
      builder: (_) => buildSubdomainTakeover(),
      category: 'Security',
    ),
    DevTool(
      id: 'subnet_calculator',
      name: 'Subnet Calculator',
      icon: Icons.lan_outlined,
      builder: (_) => buildSubnetCalculator(),
      category: 'Network',
    ),
    DevTool(
      id: 'port_scanner',
      name: 'Port Scanner',
      icon: Icons.radar,
      builder: (_) => buildPortScanner(),
      category: 'Network',
    ),
    DevTool(
      id: 'network_scanner',
      name: 'Network Scanner',
      icon: Icons.lan,
      builder: (_) => buildNetworkScanner(),
      category: 'Network',
    ),
    DevTool(
      id: 'local_server',
      name: 'Local Server',
      icon: Icons.dns,
      builder: (_) => buildLocalServer(),
      category: 'Network',
    ),
    DevTool(
      id: 'firewall_fingerprint',
      name: 'Firewall Fingerprint',
      icon: Icons.shield,
      builder: (_) => buildFirewallFingerprint(),
      category: 'Security',
    ),
    DevTool(
      id: 'html_entity_encode_decode',
      name: 'HTML Entity Encode/Decode',
      icon: Icons.html,
      builder: (_) => buildHtmlEntityEncodeDecode(),
      category: 'Encoders',
    ),
    DevTool(
      id: 'backslash_escape_unescape',
      name: 'Backslash Escape/Unescape',
      icon: Icons.wrap_text,
      builder: (_) => buildBackslashEscapeUnescape(),
      category: 'Text',
    ),
    DevTool(
      id: 'uuid_ulid_generate_decode',
      name: 'UUID/ULID Generate/Decode',
      icon: Icons.grid_3x3,
      builder: (_) => buildUuidUlid(),
      category: 'Generators',
    ),
    DevTool(
      id: 'html_preview',
      name: 'HTML Preview',
      icon: Icons.preview,
      builder: (_) => buildHtmlPreview(),
      category: 'Preview',
    ),
    DevTool(
      id: 'text_diff_checker',
      name: 'Text Diff Checker',
      icon: Icons.compare_arrows,
      builder: (_) => buildTextDiffChecker(),
      category: 'Text',
    ),
    DevTool(
      id: 'yaml_json_converter',
      name: 'YAML ↔ JSON',
      icon: Icons.swap_horiz,
      builder: (_) => buildYamlJsonConverter(),
      category: 'Converters',
    ),
    DevTool(
      id: 'number_base_converter',
      name: 'Number Base Converter',
      icon: Icons.calculate,
      builder: (_) => buildNumberBaseConverter(),
      category: 'Converters',
    ),
    DevTool(
      id: 'html_beautify_minify',
      name: 'HTML Beautify/Minify',
      icon: Icons.format_align_left,
      builder: (_) => buildHtmlBeautifyMinify('HTML'),
      category: 'Formatters',
    ),
    DevTool(
      id: 'css_beautify_minify',
      name: 'CSS Beautify/Minify',
      icon: Icons.format_align_left,
      builder: (_) => buildHtmlBeautifyMinify('CSS'),
      category: 'Formatters',
    ),
    DevTool(
      id: 'js_beautify_minify',
      name: 'JS/TS Beautify/Minify',
      icon: Icons.format_align_left,
      builder: (_) => buildHtmlBeautifyMinify('JS'),
      category: 'Formatters',
    ),
    DevTool(
      id: 'rb_beautify_minify',
      name: 'RB Beautify/Minify',
      icon: Icons.format_align_left,
      builder: (_) => buildHtmlBeautifyMinify('RB'),
      category: 'Formatters',
    ),
    DevTool(
      id: 'xml_beautify_minify',
      name: 'XML Beautify/Minify',
      icon: Icons.format_align_left,
      builder: (_) => buildXmlBeautifyMinify(),
      category: 'Formatters',
    ),
    DevTool(
      id: 'lorem_ipsum_generator',
      name: 'Lorem Ipsum Generator',
      icon: Icons.text_fields,
      builder: (_) => buildLoremIpsum(),
      category: 'Generators',
    ),
    DevTool(
      id: 'password_generator',
      name: 'Password Generator',
      icon: Icons.key,
      builder: (_) => buildPasswordGenerator(),
      category: 'Generators',
    ),
    DevTool(
      id: 'qr_code_reader_generator',
      name: 'QR Code Reader/Generator',
      icon: Icons.qr_code,
      builder: (_) => buildQrCode(),
      category: 'Generators',
    ),
    DevTool(
      id: 'semver_calculator',
      name: 'Semver Calculator',
      icon: Icons.compare_arrows,
      builder: (_) => buildSemVerCalculator(),
      category: 'Text',
    ),
    DevTool(
      id: 'string_inspector',
      name: 'String Inspector',
      icon: Icons.subject,
      builder: (_) => buildStringInspector(),
      category: 'Text',
    ),
    DevTool(
      id: 'string_case_converter',
      name: 'String Case Converter',
      icon: Icons.text_fields,
      builder: (_) => buildStringCaseConverter(),
      category: 'Text',
    ),
    DevTool(
      id: 'json_csv_converter',
      name: 'JSON ↔ CSV',
      icon: Icons.table_chart,
      builder: (_) => buildJsonCsvConverter(),
      category: 'Converters',
    ),
    DevTool(
      id: 'file_checksum',
      name: 'File Checksum',
      icon: Icons.verified_outlined,
      builder: (_) => buildFileChecksum(),
      category: 'Security',
    ),
    DevTool(
      id: 'hash_generator',
      name: 'Hash Generator',
      icon: Icons.fingerprint,
      builder: (_) => buildHashGenerator(),
      category: 'Security',
    ),
    DevTool(
      id: 'text_encryption',
      name: 'Text Encryption/Decryption',
      icon: Icons.lock,
      builder: (_) => buildTextEncryption(),
      category: 'Security',
    ),
    DevTool(
      id: 'password_hashing',
      name: 'Password Hashing',
      icon: Icons.password,
      builder: (_) => buildPasswordHashing(),
      category: 'Security',
    ),
    DevTool(
      id: 'payload_embedder',
      name: 'Payload Embed/Extract',
      icon: Icons.folder_zip,
      builder: (_) => buildPayloadEmbedder(),
      category: 'Security',
    ),
    DevTool(
      id: 'user_agent_tool',
      name: 'User Agent Generator/Validator',
      icon: Icons.language,
      builder: (_) => buildUserAgentTool(),
      category: 'Security',
    ),
    DevTool(
      id: 'antibot_detection',
      name: 'AntiBot Detection',
      icon: Icons.security,
      builder: (_) => buildAntiBotDetection(),
      category: 'Security',
    ),
    DevTool(
      id: 'offline_llm',
      name: 'Offline LLM',
      icon: Icons.smart_toy,
      builder: (_) => buildOfflineLlm(),
      category: 'AI',
    ),
    DevTool(
      id: 'html_to_jsx',
      name: 'HTML to JSX',
      icon: Icons.code,
      builder: (_) => buildHtmlToJsx(),
      category: 'Converters',
    ),
    DevTool(
      id: 'js_to_ts_converter',
      name: 'JS to TS Converter',
      icon: Icons.code,
      builder: (_) => buildJsToTsConverter(),
      category: 'Converters',
    ),
    DevTool(
      id: 'markdown_preview',
      name: 'Markdown Preview',
      icon: Icons.notes,
      builder: (_) => buildMarkdownPreview(),
      category: 'Preview',
    ),
    DevTool(
      id: 'sql_formatter',
      name: 'SQL Formatter',
      icon: Icons.storage,
      builder: (_) => buildSqlFormatter(),
      category: 'Formatters',
    ),
    DevTool(
      id: 'cron_job_parser',
      name: 'Cron Job Parser',
      icon: Icons.schedule,
      builder: (_) => buildCronJobParser(),
      category: 'Parsers',
    ),
    DevTool(
      id: 'color_converter',
      name: 'Color Converter',
      icon: Icons.palette,
      builder: (_) => buildColorConverter(),
      category: 'Converters',
    ),
    DevTool(
      id: 'php_to_js',
      name: 'PHP to JS',
      icon: Icons.code,
      builder: (_) => buildPhpToJs(),
      category: 'Converters',
    ),
    DevTool(
      id: 'php_serializer',
      name: 'PHP Serializer',
      icon: Icons.code,
      builder: (_) => buildPhpTool('PHP Serializer'),
      category: 'Text',
    ),
    DevTool(
      id: 'php_unserializer',
      name: 'PHP Unserializer',
      icon: Icons.code,
      builder: (_) => buildPhpTool('PHP Unserializer'),
      category: 'Text',
    ),
    DevTool(
      id: 'random_string_generator',
      name: 'Random String Generator',
      icon: Icons.shuffle,
      builder: (_) => buildRandomStringGenerator(),
      category: 'Generators',
    ),
    DevTool(
      id: 'svg_to_css',
      name: 'SVG to CSS',
      icon: Icons.brush,
      builder: (_) => buildSvgToCss(),
      category: 'Converters',
    ),
    DevTool(
      id: 'curl_to_code',
      name: 'cURL to Code',
      icon: Icons.send,
      builder: (_) => buildCurlToCode(),
      category: 'Converters',
    ),
    DevTool(
      id: 'json_to_code',
      name: 'JSON to Code',
      icon: Icons.code,
      builder: (_) => buildJsonToCode(),
      category: 'Generators',
    ),
    DevTool(
      id: 'cipher_decoder',
      name: 'Cipher Decoder',
      icon: Icons.lock_open,
      builder: (_) => buildCipherDecoder(),
      category: 'Security',
    ),
    DevTool(
      id: 'certificate_decoder_x509',
      name: 'Certificate Decoder (X.509)',
      icon: Icons.verified,
      builder: (_) => buildCertificateDecoder(),
      category: 'Security',
    ),
    DevTool(
      id: 'hex_ascii_converter',
      name: 'Hex ↔ ASCII',
      icon: Icons.code,
      builder: (_) => buildHexAsciiConverter(),
      category: 'Converters',
    ),
    DevTool(
      id: 'line_sort_dedupe',
      name: 'Line Sort/Dedupe',
      icon: Icons.sort,
      builder: (_) => buildLineSortDedupe(),
      category: 'Text',
    ),
    DevTool(
      id: 'uml_class_diagram',
      name: 'PlantUML Class Diagram',
      icon: Icons.account_tree,
      builder: (_) => buildUmlClassDiagram(),
      category: 'Diagrams',
    ),
    DevTool(
      id: 'chmod_calculator',
      name: 'Chmod Calculator',
      icon: Icons.lock_outline,
      builder: (_) => buildChmodCalculator(),
      category: 'Reference',
    ),
    DevTool(
      id: 'mime_types',
      name: 'MIME Types',
      icon: Icons.table_view,
      builder: (_) => buildMimeTypes(),
      category: 'Reference',
    ),
    DevTool(
      id: 'preferences',
      name: 'Preferences',
      icon: Icons.settings,
      builder: (_) => buildPreferences(),
      showDemo: false,
      category: 'Preferences',
    ),
    DevTool(
      id: 'leetspeak_converter',
      name: 'Leetspeak Converter',
      icon: Icons.abc,
      builder: (_) => buildLeetspeakConverter(),
      category: 'Text',
    ),
    DevTool(
      id: 'timestamp_extractor',
      name: 'Timestamp Extractor',
      icon: Icons.schedule,
      builder: (_) => buildTimestampExtractor(),
      category: 'Parsers',
    ),
    DevTool(
      id: 'access_log_parser',
      name: 'Access Log Parser',
      icon: Icons.receipt_long,
      builder: (_) => buildAccessLogParser(),
      category: 'Parsers',
    ),
    DevTool(
      id: 'session_cookie_decoder',
      name: 'Session Cookie Decoder',
      icon: Icons.cookie,
      builder: (_) => buildSessionCookieDecoder(),
      category: 'Security',
    ),
    DevTool(
      id: 'asn1_tlv_decoder',
      name: 'ASN.1 / TLV Decoder',
      icon: Icons.account_tree,
      builder: (_) => buildAsn1Decoder(),
      category: 'Security',
    ),
  ];

  static DevTool? byId(String id) {
    for (final tool in tools) {
      if (tool.id == id) return tool;
    }
    return null;
  }

  static String defaultPanelTitle(String id) {
    return byId(id)?.name ?? 'Tool';
  }
}
