import 'package:flutter/material.dart';

import '../models/dev_tool.dart';
import '../ui/tool_views.dart';

class ToolRegistry {
  static final List<DevTool> tools = [
    DevTool(
      id: 'unix_time_converter',
      name: 'Unix Time Converter',
      icon: Icons.schedule,
      builder: (_) => buildUnixTimeConverter(),
      subtitle: 'Convert Unix timestamps to and from calendar dates',
      category: 'Converters',
    ),
    DevTool(
      id: 'json_format_validate',
      name: 'JSON Format/Validate',
      icon: Icons.data_object,
      builder: (_) => buildJsonFormatValidate(),
      subtitle: 'Pretty-print, minify, and validate JSON as you type',
      category: 'Formatters',
    ),
    DevTool(
      id: 'base64_string_encode_decode',
      name: 'Base64 String Encode/Decode',
      icon: Icons.code,
      builder: (_) => buildBase64String(),
      subtitle: 'Encode and decode Base64 text safely',
      category: 'Encoders',
    ),
    DevTool(
      id: 'base64_image_encode_decode',
      name: 'Base64 Image Encode/Decode',
      icon: Icons.image,
      builder: (_) => buildBase64Image(),
      subtitle: 'Convert images to and from Base64 data URLs',
      category: 'Encoders',
    ),
    DevTool(
      id: 'compression_codecs',
      name: 'Compress / Decompress',
      icon: Icons.compress,
      builder: (_) => buildCompression(),
      subtitle: 'Compress and decompress text with gzip and friends',
      category: 'Compression',
    ),
    DevTool(
      id: 'base_encodings',
      name: 'Base32/58/62/85/Bech32',
      icon: Icons.tag,
      builder: (_) => buildBaseEncodings(),
      subtitle: 'Convert text between Base32, Base58, Base62, and Bech32',
      category: 'Encoders',
    ),
    DevTool(
      id: 'jwt_debugger',
      name: 'JWT Debugger',
      icon: Icons.vpn_key,
      builder: (_) => buildJwtDebugger(),
      subtitle: 'Decode, verify, and inspect JSON Web Tokens',
      category: 'Security',
    ),
    DevTool(
      id: 'auth_totp',
      name: 'Auth TOTP',
      icon: Icons.lock_clock,
      builder: (_) => buildAuthTotp(),
      subtitle: 'Generate and manage two-factor authentication codes',
      category: 'Security',
    ),
    DevTool(
      id: 'regexp_tester',
      name: 'RegExp Tester',
      icon: Icons.search,
      builder: (_) => buildRegExpTester(),
      subtitle: 'Test regular expressions with live match highlighting',
      category: 'Text',
      minSize: const Size(480, 560),
    ),
    DevTool(
      id: 'url_encode_decode',
      name: 'URL Encode/Decode',
      icon: Icons.link,
      builder: (_) => buildUrlEncodeDecode(),
      subtitle: 'Percent-encode and decode URLs and query values',
      category: 'Encoders',
    ),
    DevTool(
      id: 'url_parser',
      name: 'URL Parser',
      icon: Icons.link_outlined,
      builder: (_) => buildUrlParser(),
      subtitle: 'Inspect URLs and send HTTP requests',
      isOffline: false,
      category: 'Parsers',
    ),
    DevTool(
      id: 'subdomain_finder',
      name: 'Subdomain Finder',
      icon: Icons.travel_explore,
      builder: (_) => buildSubdomainFinder(),
      subtitle: 'Discover subdomains via certificate transparency logs',
      category: 'Network',
      minSize: const Size(480, 560),
      isOffline: false,
    ),
    DevTool(
      id: 'subdomain_takeover',
      name: 'Subdomain Takeover Check',
      icon: Icons.domain_verification,
      builder: (_) => buildSubdomainTakeover(),
      subtitle: 'Check subdomains for takeover-vulnerable records',
      category: 'Security',
      minSize: const Size(480, 600),
      isOffline: false,
    ),
    DevTool(
      id: 'subnet_calculator',
      name: 'Subnet Calculator',
      icon: Icons.lan_outlined,
      builder: (_) => buildSubnetCalculator(),
      subtitle: 'IPv4 CIDR notation and subnet masks at a glance',
      category: 'Network',
    ),
    DevTool(
      id: 'port_scanner',
      name: 'Port Scanner',
      icon: Icons.radar,
      builder: (_) => buildPortScanner(),
      subtitle: 'Probe TCP ports with profiles and banner grabs',
      category: 'Network',
      minSize: const Size(560, 540),
      isOffline: false,
    ),
    DevTool(
      id: 'network_scanner',
      name: 'Network Scanner',
      icon: Icons.lan,
      builder: (_) => buildNetworkScanner(),
      subtitle: 'Sweep LAN ranges for live hosts and open ports',
      category: 'Network',
      minSize: const Size(580, 600),
      isOffline: false,
    ),
    DevTool(
      id: 'local_server',
      name: 'Local Server',
      icon: Icons.dns,
      builder: (_) => buildLocalServer(),
      subtitle: 'Serve files locally with live request logging',
      category: 'Network',
      isOffline: false,
    ),
    DevTool(
      id: 'firewall_fingerprint',
      name: 'Firewall Fingerprint',
      icon: Icons.shield,
      builder: (_) => buildFirewallFingerprint(),
      subtitle: 'Detect firewalls and WAFs from response fingerprints',
      category: 'Security',
      minSize: const Size(480, 500),
      isOffline: false,
    ),
    DevTool(
      id: 'html_entity_encode_decode',
      name: 'HTML Entity Encode/Decode',
      icon: Icons.html,
      builder: (_) => buildHtmlEntityEncodeDecode(),
      subtitle: 'Escape and unescape HTML entities',
      category: 'Encoders',
    ),
    DevTool(
      id: 'backslash_escape_unescape',
      name: 'Backslash Escape/Unescape',
      icon: Icons.wrap_text,
      builder: (_) => buildBackslashEscapeUnescape(),
      subtitle: 'Escape and unescape backslash and C-style sequences',
      category: 'Text',
    ),
    DevTool(
      id: 'uuid_ulid_generate_decode',
      name: 'UUID/ULID Generate/Decode',
      icon: Icons.grid_3x3,
      builder: (_) => buildUuidUlid(),
      subtitle: 'Generate and decode UUIDs and ULIDs',
      category: 'Generators',
      minSize: const Size(480, 520),
    ),
    DevTool(
      id: 'html_preview',
      name: 'HTML Preview',
      icon: Icons.preview,
      builder: (_) => buildHtmlPreview(),
      subtitle: 'Render HTML with a live sandboxed preview',
      category: 'Preview',
    ),
    DevTool(
      id: 'text_diff_checker',
      name: 'Text Diff Checker',
      icon: Icons.compare_arrows,
      builder: (_) => buildTextDiffChecker(),
      subtitle: 'Compare two texts with line-level diffs',
      category: 'Text',
      minSize: const Size(480, 520),
    ),
    DevTool(
      id: 'yaml_json_converter',
      name: 'YAML ↔ JSON',
      icon: Icons.swap_horiz,
      builder: (_) => buildYamlJsonConverter(),
      subtitle: 'Convert between YAML and JSON in both directions',
      category: 'Converters',
    ),
    DevTool(
      id: 'number_base_converter',
      name: 'Number Base Converter',
      icon: Icons.calculate,
      builder: (_) => buildNumberBaseConverter(),
      subtitle: 'Convert integers between binary, decimal, hex, and custom bases',
      category: 'Converters',
      minSize: const Size(480, 360),
    ),
    DevTool(
      id: 'html_beautify_minify',
      name: 'HTML Beautify/Minify',
      icon: Icons.format_align_left,
      builder: (_) => buildHtmlBeautifyMinify('HTML'),
      subtitle: 'Beautify or minify HTML markup',
      category: 'Formatters',
    ),
    DevTool(
      id: 'css_beautify_minify',
      name: 'CSS Beautify/Minify',
      icon: Icons.format_align_left,
      builder: (_) => buildHtmlBeautifyMinify('CSS'),
      subtitle: 'Beautify or minify CSS stylesheets',
      category: 'Formatters',
    ),
    DevTool(
      id: 'js_beautify_minify',
      name: 'JS/TS Beautify/Minify',
      icon: Icons.format_align_left,
      builder: (_) => buildHtmlBeautifyMinify('JS'),
      subtitle: 'Beautify or minify JavaScript and TypeScript',
      category: 'Formatters',
    ),
    DevTool(
      id: 'rb_beautify_minify',
      name: 'RB Beautify/Minify',
      icon: Icons.format_align_left,
      builder: (_) => buildHtmlBeautifyMinify('RB'),
      subtitle: 'Beautify or minify Ruby code',
      category: 'Formatters',
    ),
    DevTool(
      id: 'xml_beautify_minify',
      name: 'XML Beautify/Minify',
      icon: Icons.format_align_left,
      builder: (_) => buildXmlBeautifyMinify(),
      subtitle: 'Beautify or minify XML documents',
      category: 'Formatters',
    ),
    DevTool(
      id: 'lorem_ipsum_generator',
      name: 'Lorem Ipsum Generator',
      icon: Icons.text_fields,
      builder: (_) => buildLoremIpsum(),
      subtitle: 'Generate placeholder text by words, sentences, or paragraphs',
      category: 'Generators',
      minSize: const Size(580, 280),
    ),
    DevTool(
      id: 'password_generator',
      name: 'Password Generator',
      icon: Icons.key,
      builder: (_) => buildPasswordGenerator(),
      subtitle: 'Create strong random passwords with custom rules',
      category: 'Generators',
      minSize: const Size(580, 280),
    ),
    DevTool(
      id: 'qr_code_reader_generator',
      name: 'QR Code Reader/Generator',
      icon: Icons.qr_code,
      builder: (_) => buildQrCode(),
      subtitle: 'Generate QR codes and read them from images',
      category: 'Generators',
    ),
    DevTool(
      id: 'semver_calculator',
      name: 'Semver Calculator',
      icon: Icons.compare_arrows,
      builder: (_) => buildSemVerCalculator(),
      subtitle: 'Compare semantic versions and preview version bumps',
      category: 'Text',
      minSize: const Size(660, 280),
    ),
    DevTool(
      id: 'string_inspector',
      name: 'String Inspector',
      icon: Icons.subject,
      builder: (_) => buildStringInspector(),
      subtitle: 'Inspect length, bytes, characters, and line stats',
      category: 'Text',
    ),
    DevTool(
      id: 'string_case_converter',
      name: 'String Case Converter',
      icon: Icons.text_fields,
      builder: (_) => buildStringCaseConverter(),
      subtitle: 'Convert text between camel, snake, kebab, and title cases',
      category: 'Text',
    ),
    DevTool(
      id: 'json_csv_converter',
      name: 'JSON ↔ CSV',
      icon: Icons.table_chart,
      builder: (_) => buildJsonCsvConverter(),
      subtitle: 'Convert between JSON and CSV tables',
      category: 'Converters',
    ),
    DevTool(
      id: 'file_checksum',
      name: 'File Checksum',
      icon: Icons.verified_outlined,
      builder: (_) => buildFileChecksum(),
      subtitle: 'Hash files with MD5, SHA-1, SHA-256, and more',
      category: 'Security',
    ),
    DevTool(
      id: 'hash_generator',
      name: 'Hash Generator',
      icon: Icons.fingerprint,
      builder: (_) => buildHashGenerator(),
      subtitle: 'Hash text with dozens of algorithms',
      category: 'Security',
    ),
    DevTool(
      id: 'text_encryption',
      name: 'Text Encryption/Decryption',
      icon: Icons.lock,
      builder: (_) => buildTextEncryption(),
      subtitle: 'Encrypt and decrypt text with symmetric ciphers',
      category: 'Security',
      minSize: const Size(480, 480),
    ),
    DevTool(
      id: 'password_hashing',
      name: 'Password Hashing',
      icon: Icons.password,
      builder: (_) => buildPasswordHashing(),
      subtitle: 'Hash and verify passwords with adaptive KDFs',
      category: 'Security',
    ),
    DevTool(
      id: 'payload_embedder',
      name: 'Payload Embed/Extract',
      icon: Icons.folder_zip,
      builder: (_) => buildPayloadEmbedder(),
      subtitle: 'Embed and extract payloads around template markers',
      category: 'Security',
    ),
    DevTool(
      id: 'user_agent_tool',
      name: 'User Agent Generator/Validator',
      icon: Icons.language,
      builder: (_) => buildUserAgentTool(),
      subtitle: 'Generate and validate realistic user-agent strings',
      category: 'Security',
    ),
    DevTool(
      id: 'antibot_detection',
      name: 'AntiBot Detection',
      icon: Icons.security,
      builder: (_) => buildAntiBotDetection(),
      subtitle: 'Identify anti-bot protections from page fingerprints',
      category: 'Security',
    ),
    DevTool(
      id: 'offline_llm',
      name: 'Offline LLM',
      icon: Icons.smart_toy,
      builder: (_) => buildOfflineLlm(),
      subtitle: 'Run local language models privately on your machine',
      category: 'AI',
      minSize: const Size(480, 560),
    ),
    DevTool(
      id: 'html_to_jsx',
      name: 'HTML to JSX',
      icon: Icons.code,
      builder: (_) => buildHtmlToJsx(),
      subtitle: 'Convert HTML markup into JSX components',
      category: 'Converters',
    ),
    DevTool(
      id: 'js_to_ts_converter',
      name: 'JS to TS Converter',
      icon: Icons.code,
      builder: (_) => buildJsToTsConverter(),
      subtitle: 'Annotate JavaScript with inferred TypeScript types',
      category: 'Converters',
    ),
    DevTool(
      id: 'markdown_preview',
      name: 'Markdown Preview',
      icon: Icons.notes,
      builder: (_) => buildMarkdownPreview(),
      subtitle: 'Write Markdown with an instant rendered preview',
      category: 'Preview',
    ),
    DevTool(
      id: 'sql_formatter',
      name: 'SQL Formatter',
      icon: Icons.storage,
      builder: (_) => buildSqlFormatter(),
      subtitle: 'Format and beautify SQL queries',
      category: 'Formatters',
    ),
    DevTool(
      id: 'cron_job_parser',
      name: 'Cron Job Parser',
      icon: Icons.schedule,
      builder: (_) => buildCronJobParser(),
      subtitle: 'Explain cron expressions and upcoming runs',
      category: 'Parsers',
    ),
    DevTool(
      id: 'color_converter',
      name: 'Color Converter',
      icon: Icons.palette,
      builder: (_) => buildColorConverter(),
      subtitle: 'Convert between hex, RGB, HSL, and named colors',
      category: 'Converters',
    ),
    DevTool(
      id: 'php_to_js',
      name: 'PHP to JS',
      icon: Icons.code,
      builder: (_) => buildPhpToJs(),
      subtitle: 'Translate PHP snippets into JavaScript',
      category: 'Converters',
    ),
    DevTool(
      id: 'php_serializer',
      name: 'PHP Serializer',
      icon: Icons.code,
      builder: (_) => buildPhpTool('PHP Serializer'),
      subtitle: 'Serialize values into the PHP wire format',
      category: 'Text',
    ),
    DevTool(
      id: 'php_unserializer',
      name: 'PHP Unserializer',
      icon: Icons.code,
      builder: (_) => buildPhpTool('PHP Unserializer'),
      subtitle: 'Unpack PHP serialized payloads',
      category: 'Text',
    ),
    DevTool(
      id: 'random_string_generator',
      name: 'Random String Generator',
      icon: Icons.shuffle,
      builder: (_) => buildRandomStringGenerator(),
      subtitle: 'Generate random strings with custom alphabets',
      category: 'Generators',
      minSize: const Size(600, 280),
    ),
    DevTool(
      id: 'svg_to_css',
      name: 'SVG to CSS',
      icon: Icons.brush,
      builder: (_) => buildSvgToCss(),
      subtitle: 'Turn SVG markup into CSS backgrounds and masks',
      category: 'Converters',
    ),
    DevTool(
      id: 'curl_to_code',
      name: 'cURL to Code',
      icon: Icons.send,
      builder: (_) => buildCurlToCode(),
      subtitle: 'Convert cURL commands into code in many languages',
      category: 'Converters',
    ),
    DevTool(
      id: 'json_to_code',
      name: 'JSON to Code',
      icon: Icons.code,
      builder: (_) => buildJsonToCode(),
      subtitle: 'Generate typed models from JSON samples',
      category: 'Generators',
    ),
    DevTool(
      id: 'cipher_decoder',
      name: 'Cipher Decoder',
      icon: Icons.lock_open,
      builder: (_) => buildCipherDecoder(),
      subtitle: 'Decode classic ciphers like Caesar, Vigenere, and ROT13',
      category: 'Security',
    ),
    DevTool(
      id: 'certificate_decoder_x509',
      name: 'Certificate Decoder (X.509)',
      icon: Icons.verified,
      builder: (_) => buildCertificateDecoder(),
      subtitle: 'Decode X.509 certificates from PEM or DER',
      category: 'Security',
    ),
    DevTool(
      id: 'hex_ascii_converter',
      name: 'Hex ↔ ASCII',
      icon: Icons.code,
      builder: (_) => buildHexAsciiConverter(),
      subtitle: 'Convert between hex bytes and ASCII text',
      category: 'Converters',
    ),
    DevTool(
      id: 'line_sort_dedupe',
      name: 'Line Sort/Dedupe',
      icon: Icons.sort,
      builder: (_) => buildLineSortDedupe(),
      subtitle: 'Sort, deduplicate, and clean lines of text',
      category: 'Text',
    ),
    DevTool(
      id: 'uml_class_diagram',
      name: 'PlantUML Class Diagram',
      icon: Icons.account_tree,
      builder: (_) => buildUmlClassDiagram(),
      subtitle: 'Draft PlantUML class diagrams and export them as PNG',
      category: 'Diagrams',
    ),
    DevTool(
      id: 'chmod_calculator',
      name: 'Chmod Calculator',
      icon: Icons.lock_outline,
      builder: (_) => buildChmodCalculator(),
      subtitle: 'Translate Unix permission bits to and from octal',
      category: 'Reference',
      minSize: const Size(480, 420),
    ),
    DevTool(
      id: 'mime_types',
      name: 'MIME Types',
      icon: Icons.table_view,
      builder: (_) => buildMimeTypes(),
      subtitle: 'Look up MIME types by name, type, or extension',
      category: 'Reference',
      minSize: const Size(500, 280),
    ),
    DevTool(
      id: 'preferences',
      name: 'Preferences',
      icon: Icons.settings,
      builder: (_) => buildPreferences(),
      subtitle: 'Theme, appearance, and app settings',
      showDemo: false,
      category: 'Preferences',
    ),
    DevTool(
      id: 'leetspeak_converter',
      name: 'Leetspeak Converter',
      icon: Icons.abc,
      builder: (_) => buildLeetspeakConverter(),
      subtitle: 'Convert text to and from leetspeak',
      category: 'Text',
    ),
    DevTool(
      id: 'timestamp_extractor',
      name: 'Timestamp Extractor',
      icon: Icons.schedule,
      builder: (_) => buildTimestampExtractor(),
      subtitle: 'Find and decode timestamps hidden in text',
      category: 'Parsers',
    ),
    DevTool(
      id: 'access_log_parser',
      name: 'Access Log Parser',
      icon: Icons.receipt_long,
      builder: (_) => buildAccessLogParser(),
      subtitle: 'Parse and summarize web server access logs',
      category: 'Parsers',
    ),
    DevTool(
      id: 'session_cookie_decoder',
      name: 'Session Cookie Decoder',
      icon: Icons.cookie,
      builder: (_) => buildSessionCookieDecoder(),
      subtitle: 'Decode session cookies from popular frameworks',
      category: 'Security',
    ),
    DevTool(
      id: 'asn1_tlv_decoder',
      name: 'ASN.1 / TLV Decoder',
      icon: Icons.account_tree,
      builder: (_) => buildAsn1Decoder(),
      subtitle: 'Decode ASN.1 TLV structures from hex or Base64',
      category: 'Security',
    ),
    DevTool(
      id: 'js_obfuscator',
      name: 'JS/TS Obfuscator',
      icon: Icons.blur_on,
      builder: (_) => buildJsObfuscator(),
      subtitle: 'Obfuscate JavaScript and TypeScript for shipping',
      category: 'Security',
    ),
    DevTool(
      id: 'hash_verifier',
      name: 'Hash/HMAC Verifier',
      icon: Icons.fact_check,
      builder: (_) => buildHashVerifier(),
      subtitle: 'Verify text or files against published digests and HMACs',
      category: 'Security',
    ),
    DevTool(
      id: 'query_editor',
      name: 'URL Query Editor',
      icon: Icons.link,
      builder: (_) => buildQueryEditor(),
      subtitle: 'Add, sort, and inspect URL query parameters',
      category: 'Parsers',
    ),
    DevTool(
      id: 'csv_inspector',
      name: 'CSV Inspector',
      icon: Icons.table_rows,
      builder: (_) => buildCsvInspector(),
      subtitle: 'Filter, sort, and inspect CSV data',
      category: 'Parsers',
    ),
    DevTool(
      id: 'date_difference',
      name: 'Date/Time Difference',
      icon: Icons.date_range,
      builder: (_) => buildDateDifference(),
      subtitle: 'Calculate elapsed time between dates across time zones',
      category: 'Converters',
    ),
  ];

  static DevTool? byId(String id) {
    for (final tool in tools) {
      if (tool.id == id) return tool;
    }
    return null;
  }

  static String defaultPanelTitle(String id) {
    return byId(id)?.name ?? 'Tool';
  }
}
