import 'package:flutter/material.dart' show Size;
import 'package:flutter_test/flutter_test.dart';

import 'package:dev_tool/services/asn1_service.dart';
import 'package:dev_tool/services/leetspeak_service.dart';
import 'package:dev_tool/services/log_parser_service.dart';
import 'package:dev_tool/services/session_cookie_service.dart';
import 'package:dev_tool/services/timestamp_service.dart';

import '../helpers/tool_harness.dart';

void toolTest(
  String description,
  String toolId,
  Future<void> Function(ToolHarness h) body,
) {
  testWidgets(description, (tester) async {
    final h = ToolHarness(tester);
    await h.open(toolId, surface: const Size(1500, 1000));
    await body(h);
  });
}

/// EditorPane moves Sample into a right-click menu as 'Example'.
Future<void> loadSample(ToolHarness h) async {
  await h.tap('Load sample');
  await h.settle();
}

/// Generated by a real `itsdangerous`-signed Flask session, so the decoder is
/// checked against the actual wire format rather than a hand-written guess.
const _flaskCookie =
    'eyJfdXNlcl9pZCI6IjEiLCJjYXJ0IjpbImEiLCJiIl0sImNzcmZfdG9rZW4iOiJ4eXoifQ'
    '.asfX7Q.59fSDM_OJOr-Ik5lbIv2TKTF2v8';

/// Builds a DER time TLV whose content is [text].
Asn1Outcome _timeValue(int tag, String text) {
  final bytes = text.codeUnits;
  return decodeAsn1([tag, bytes.length, ...bytes]);
}

const _bcryptHash =
    r'$2a$10$9XyZq0kQvT1nB5wLp3Rt7uKjH2sF8dG4mN6pQ1rS5tV7xY3zA0bC';

void main() {
  group('leetspeak service', () {
    test('decodes digits back to letters', () {
      final result = decodeLeetSync('H3ll0 W0rld', LeetProfile.basic);
      expect(result.error, isNull);
      expect(result.output, 'Hello World');
    });

    test('counts the substitutions it made', () {
      final result = decodeLeetSync('1337', LeetProfile.common);
      expect(result.replacements['3'], 2);
      // '7' only exists in the wider profiles, not in basic.
      expect(result.replacements['7'], 1);
      expect(result.replacements['1'], 1);
    });

    test('basic profile keeps the wider symbols intact', () {
      expect(decodeLeetSync('7', LeetProfile.basic).output, '7');
      expect(decodeLeetSync('7', LeetProfile.common).output, 't');
    });

    test('leaves plain text untouched', () {
      final result = decodeLeetSync('Hello World', LeetProfile.basic);
      expect(result.output, 'Hello World');
    });

    test('rejects empty input instead of guessing', () {
      expect(decodeLeetSync('', LeetProfile.basic).error, isNotNull);
    });

    test('basic profile does not touch every symbol', () {
      // '$' and '!' are aggressive-profile substitutions.
      expect(decodeLeetSync('h!', LeetProfile.basic).output, 'h!');
      expect(decodeLeetSync('h!', LeetProfile.aggressive).output, 'hi');
    });
  });

  group('timestamp service', () {
    test('parses ISO 8601 with an explicit zone', () {
      final hit = extractTimestamps('at 2026-03-08T09:12:01Z now').hits.single;
      expect(hit.instant.toIso8601String(), '2026-03-08T09:12:01.000Z');
      expect(hit.assumeUtc, isFalse);
    });

    test('normalises the Apache offset to UTC', () {
      // The canonical Apache example: -0700 is 20:55:36 UTC.
      final hit = extractTimestamps(
        '[10/Oct/2000:13:55:36 -0700]',
        format: TimestampFormat.apache,
      ).hits.single;
      expect(hit.instant.toIso8601String(), '2000-10-10T20:55:36.000Z');
    });

    test('detects epoch seconds and milliseconds distinctly', () {
      final hits = extractTimestamps('1700000000 1700000000123').hits;
      expect(hits.length, 2);
      expect(hits.first.instant.millisecondsSinceEpoch, 1700000000000);
      expect(hits.last.instant.millisecondsSinceEpoch, 1700000000123);
    });

    test('finds every format in mixed text', () {
      final hits = extractTimestamps(
        const [
          '2026-03-08T09:12:01Z',
          '08/Mar/2024:09:12:05 +0000',
          '1700000000',
        ].join(' '),
      ).hits;
      expect(hits.length, greaterThanOrEqualTo(3));
    });

    test('reports an error for blank input', () {
      expect(extractTimestamps('   ').error, isNotNull);
    });

    test('reports when nothing matched', () {
      expect(extractTimestamps('no dates in here').hits, isEmpty);
    });

    test('records character offsets for highlighting', () {
      final hit = extractTimestamps('xx 1700000000').hits.single;
      expect(hit.start, 3);
      expect(hit.raw, '1700000000');
    });
  });

  group('session cookie service', () {
    test('decodes a real Flask session cookie', () {
      final outcome = decodeSession(_flaskCookie);
      expect(outcome.format, SessionFormat.flask);
      final payload = outcome.parts.firstWhere((p) => p.name == 'Payload');
      expect(payload.value, contains('_user_id'));
      expect(payload.value, contains('csrf_token'));
    });

    test('decodes the itsdangerous integer timestamp segment', () {
      final outcome = decodeSession(_flaskCookie);
      final issued = outcome.parts.firstWhere((p) => p.name == 'Issued at');
      // The segment is a big-endian integer, not ASCII text.
      expect(issued.value, matches(r'^20\d\d-\d\d-\d\dT'));
    });

    test('warns that Flask signatures are not verified offline', () {
      expect(decodeSession(_flaskCookie).warnings, isNotEmpty);
    });

    test('does not mistake a bcrypt hash for a Flask cookie', () {
      expect(decodeSession(_bcryptHash).format, SessionFormat.unknown);
    });

    test('recognises a JWE by its five segments', () {
      const jwe =
          'eyJhbGciOiJSU0EtT0FFUCJ9'
          '.eyJzdWIiOiIxMjM0NTY3ODkwIn0'
          '.eyJhbGciOiJSU0EtT0FFUCJ9'
          '.c2ln'
          '.c2ln';
      expect(decodeSession(jwe).format, SessionFormat.jwe);
    });

    test('recognises a JWT by its header object', () {
      const jwt = 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.abc123';
      expect(decodeSession(jwt).format, SessionFormat.jwt);
    });

    test('reports unknown for undecodable input', () {
      expect(
        decodeSession('!!! not a cookie !!!').format,
        SessionFormat.unknown,
      );
    });

    test('renders parts and caveats into a report', () {
      final report = renderSessionReport(decodeSession(_flaskCookie));
      expect(report, contains('Flask session cookie'));
      expect(report, contains('PAYLOAD'));
      expect(report, contains('Keep in mind'));
    });
  });

  group('asn1 service', () {
    test('decodes a nested SEQUENCE', () {
      final outcome = decodeAsn1(const [
        0x30,
        0x06,
        0x02,
        0x01,
        0x05,
        0x02,
        0x01,
        0x2A,
      ]);
      expect(outcome.error, isNull);
      // The SEQUENCE and its two INTEGER children.
      expect(outcome.nodeCount, 3);
      expect(outcome.roots.single.children, hasLength(2));
      expect(outcome.roots.single.children.first.value, '5');
      expect(outcome.roots.single.children.last.value, '42');
    });

    test('decodes long-form lengths', () {
      final payload = List<int>.filled(200, 0x41);
      final outcome = decodeAsn1([0x04, 0x81, 0xC8, ...payload]);
      expect(outcome.error, isNull);
      expect(outcome.roots.single.content, hasLength(200));
    });

    test('decodes OBJECT IDENTIFIER to dotted form', () {
      // 1.2.840.113549.1.1.11 = sha256WithRSAEncryption
      final outcome = decodeAsn1(const [
        0x06,
        0x09,
        0x2A,
        0x86,
        0x48,
        0x86,
        0xF7,
        0x0D,
        0x01,
        0x01,
        0x0B,
      ]);
      expect(outcome.roots.single.value, '1.2.840.113549.1.1.11');
    });

    test('reads a negative INTEGER as signed', () {
      // 0xFF is -1 in two's complement.
      expect(decodeAsn1(const [0x02, 0x01, 0xFF]).roots.single.value, '-1');
    });

    test('reads BOOLEAN and NULL', () {
      expect(decodeAsn1(const [0x01, 0x01, 0xFF]).roots.single.value, 'TRUE');
      expect(
        decodeAsn1(const [0x05, 0x00]).roots.single.universalLabel,
        'NULL',
      );
    });

    test('reads UTCTime against the X.690 century rule', () {
      // 261008175317Z is 2026, and 481231235959Z is 2048.
      expect(
        _timeValue(0x17, '261008175317Z').roots.single.value,
        contains('2026-10-08T17:53:17'),
      );
      expect(
        _timeValue(0x17, '481231235959Z').roots.single.value,
        contains('2048-12-31T23:59:59'),
      );
      expect(
        _timeValue(0x17, '500101000000Z').roots.single.value,
        contains('1950-01-01T00:00:00'),
      );
    });

    test('reads GeneralizedTime with fractional seconds', () {
      expect(
        _timeValue(0x18, '20240308091201.500Z').roots.single.value,
        contains('2024-03-08T09:12:01.500'),
      );
    });

    test('reports truncation instead of throwing', () {
      final outcome = decodeAsn1(const [0x30, 0x10, 0x02, 0x01]);
      expect(outcome.error, isNotNull);
    });

    test('keeps the nodes it could read when one child is malformed', () {
      // 0x5F is constructed but its content is not valid TLV.
      // 0x6F is an EMV template, so its six content bytes are parsed as
      // nested TLV: 0x5F claims four bytes, then 0x41 claims 0x42, which
      // runs past the end.
      final outcome = decodeAsn1(const [
        0x6F,
        0x06,
        0x5F,
        0x04,
        0x41,
        0x42,
        0x43,
        0x44,
      ], mode: Asn1DecodeMode.berTlv);
      expect(outcome.error, isNull);
      final template = outcome.roots.single.children.single;
      expect(template.tagNumber, 0x5F);
      expect(template.constructed, isTrue);
      expect(template.truncated, isTrue);
    });

    test('treats EMV tags as literal bytes, not ASN.1 tag numbers', () {
      final outcome = decodeAsn1(const [
        0x6F,
        0x0B,
        0x84,
        0x01,
        0x01,
        0x02,
        0x01,
        0x1E,
        0x5F,
        0x03,
        0xA0,
        0x01,
        0x41,
      ], mode: Asn1DecodeMode.berTlv);
      expect(outcome.error, isNull);
      final report = renderAsn1Report(outcome);
      expect(report, contains('Tag 0x6f'));
      expect(report, contains('Tag 0x84'));
      expect(report, contains('Tag 0x5f'));
      // EMV templates recurse even though b6 is clear.
      expect(outcome.roots.single.children, hasLength(3));
    });

    test('still expands ASN.1 high-tag-number form', () {
      // 0x1F is the high-tag-number marker; 0x81 0x20 encodes tag 160.
      final outcome = decodeAsn1(const [0x1F, 0x81, 0x20, 0x01, 0xAB]);
      expect(outcome.error, isNull);
      expect(outcome.roots.single.tagNumber, 160);
      expect(outcome.roots.single.content, const [0xAB]);
    });

    test('rejects empty input', () {
      expect(decodeAsn1(const []).error, isNotNull);
    });
  });

  group('access log service', () {
    test('parses an Apache combined line end to end', () {
      final entry = parseLogLine(
        '127.0.0.1 - frank [10/Oct/2000:13:55:36 -0700] '
        '"GET /apache_pb.gif HTTP/1.0" 200 2326 '
        '"http://example.com/start" "Mozilla/4.08"',
        1,
      )!;
      expect(entry.format, LogFormat.combined);
      expect(entry.client, '127.0.0.1');
      expect(entry.user, 'frank');
      expect(entry.status, 200);
      expect(entry.bytes, 2326);
      expect(entry.timestamp!.toIso8601String(), '2000-10-10T20:55:36.000Z');
      expect(entry.lineage, isNull);
    });

    test('separates the path from its query string', () {
      final entry = parseLogLine(
        '10.0.0.1 - - [08/Mar/2024:09:12:01 +0000] '
        '"GET /api/users?id=7 HTTP/1.1" 200 10',
        1,
      )!;
      expect(entry.pathOnly, '/api/users');
      expect(entry.query, 'id=7');
      expect(entry.format, LogFormat.common);
    });

    test('parses a JSON access line', () {
      final entry = parseLogLine(
        '{"time":"2024-03-08T09:12:09Z","remote_addr":"198.51.100.4",'
        '"status":200,"request_uri":"GET /health HTTP/1.1",'
        '"request_time":0.004}',
        1,
      )!;
      expect(entry.format, LogFormat.json);
      expect(entry.method, 'GET');
      expect(entry.path, '/health');
      expect(entry.requestTime, 0.004);
    });

    test('reads request_time appended by a custom nginx format', () {
      final entry = parseLogLine(
        '10.0.0.1 - - [08/Mar/2024:09:12:01 +0000] '
        '"GET /slow HTTP/1.1" 200 10 "-" "curl/8.4.0" 1.750',
        1,
      )!;
      expect(entry.requestTime, closeTo(1.75, 0.001));
    });

    test('flags an unrecognised line instead of dropping it', () {
      final outcome = parseAccessLog('garbage line that is not a log entry');
      expect(outcome.entries.single.lineage, isNotNull);
      expect(outcome.summary.unparsed, 1);
      expect(outcome.summary.parsed, 0);
    });

    test('aggregates status classes and errors', () {
      final outcome = parseAccessLog(
        const [
          'a - - [08/Mar/2024:09:12:01 +0000] "GET /a HTTP/1.1" 200 10',
          'b - - [08/Mar/2024:09:12:02 +0000] "GET /b HTTP/1.1" 404 0',
          'c - - [08/Mar/2024:09:12:03 +0000] "GET /c HTTP/1.1" 500 0',
        ].join('\n'),
      );
      expect(outcome.summary.parsed, 3);
      expect(outcome.summary.errors['4xx'], 1);
      expect(outcome.summary.errors['5xx'], 1);
      expect(outcome.summary.statusClasses['2xx'], 1);
    });

    test('counts blank lines without treating them as entries', () {
      final outcome = parseAccessLog(
        '\n\na - - [08/Mar/2024:09:12:01 +0000] '
        '"GET /a HTTP/1.1" 200 10\n',
      );
      // Two leading blank lines then one entry.
      expect(outcome.blankLines, 2);
      expect(outcome.summary.total, 3);
      expect(outcome.entries, hasLength(1));
    });

    test('lists the slowest requests first', () {
      final outcome = parseAccessLog(
        const [
          'a - - [08/Mar/2024:09:12:01 +0000] "GET /a HTTP/1.1" 200 10 "-" "c" 0.100',
          'b - - [08/Mar/2024:09:12:02 +0000] "GET /b HTTP/1.1" 200 10 "-" "c" 3.500',
        ].join('\n'),
      );
      expect(outcome.summary.slowest.first.path, '/b');
    });

    test('handles an empty log without throwing', () {
      final outcome = parseAccessLog('');
      expect(outcome.entries, isEmpty);
      expect(renderLogTable(outcome), 'No log lines found.');
    });
  });

  group('leetspeak view', () {
    toolTest('decodes the loaded sample', 'leetspeak_converter', (h) async {
      await loadSample(h);
      expect(h.text('H3ll0 W0rld'), 'H3ll0 W0rld 1337 sp34k');
      // The basic profile maps 3 -> e and leaves 7 alone.
      expect(h.text('Hello World'), 'Hello World iee7 speak');
    });

    toolTest(
      'a wider profile decodes the same sample further',
      'leetspeak_converter',
      (h) async {
        await loadSample(h);
        await h.tap('Common');
        // 1 -> i, 3 -> e, 7 -> t.
        expect(h.text('Hello World'), 'Hello World ieet speak');
      },
    );

    toolTest(
      'converts plain text to leet in encode mode',
      'leetspeak_converter',
      (h) async {
        await h.enter('H3ll0 W0rld', text: 'Hello World');
        expect(h.text('Hello World'), contains('H'));
      },
    );
  });

  group('timestamp view', () {
    toolTest('reports detections from the sample', 'timestamp_extractor', (
      h,
    ) async {
      await loadSample(h);
      expect(h.text('Detected timestamps'), contains('1700000000'));
    });

    toolTest('reports when nothing is found', 'timestamp_extractor', (h) async {
      await h.enter(
        'Paste text containing timestamps',
        text: 'nothing here at all',
      );
      expect(h.text('Detected timestamps'), 'No timestamps found.');
    });
  });

  group('session cookie view', () {
    toolTest('decodes the sample Flask cookie', 'session_cookie_decoder', (
      h,
    ) async {
      await loadSample(h);
      expect(h.text('Decoded contents'), contains('Flask session cookie'));
    });
  });

  group('asn1 view', () {
    toolTest('decodes hex sample input', 'asn1_tlv_decoder', (h) async {
      await loadSample(h);
      expect(h.text('Tag tree'), contains('SEQUENCE'));
      expect(h.text('Tag tree'), contains('UTF8String'));
    });

    toolTest('switches to generic TLV mode', 'asn1_tlv_decoder', (h) async {
      await h.tap('Generic TLV');
      await loadSample(h);
      expect(h.text('Tag tree'), contains('Tag 0x6f'));
      expect(h.text('Tag tree'), contains('Tag 0x5f'));
    });

    toolTest(
      'surfaces a helpful error for malformed input',
      'asn1_tlv_decoder',
      (h) async {
        await h.enter(
          'Paste a PEM certificate or DER/hex bytes',
          text: 'not hex ~~ here',
        );
        expect(
          find.text('Input is neither PEM, Base64, nor hex.'),
          findsOneWidget,
        );
      },
    );
  });

  group('access log view', () {
    toolTest('parses the sample log', 'access_log_parser', (h) async {
      await loadSample(h);
      expect(h.text('Parsed fields'), contains('apache_pb.gif'));
    });

    toolTest('switches to the summary view', 'access_log_parser', (h) async {
      await loadSample(h);
      await h.tap('Summary');
      expect(h.text('Parsed fields'), contains('Status classes'));
    });
  });
}
